### PR TITLE
Creates libpar2, fixes bugs, filename standards, etc.

### PR DESCRIPTION
**Pull request by mdnahas**
HUGE change.  I created a static library called "libpar2", that tools can use to create or repair par2 files.  The commandline interface now just calls libpar2.  

There are a lot of other small changes.  I've detailed them below.  Many are bug fixes found by new unit tests and running the tools Cppcheck and Valgrind.  

I need a day or two more on these changes, but I'm pushing the fork now so that people can help test it. 
 (I still need to write some documentation and test that Par2 files generated by the old code can be decoded by the new code.  I'm not really worried about that problem, but I definitely want to run the test before merging this fork!)

There are tests for a lot of my changes, but **please help me test this huge change by compiling on your system and running the tests.**  I tested it on Linux and an old OSX box that I own.  I installed MinGW and Wine to test the Windows code, but **we really need to test this with the Microsoft compiler before merging.**  I did changes to # ifdefs in libpar2.h and par2cmdline.h and I used the new type "unique_ptr" that could cause problem.  

The full list of changes is below.  Sorry for making it so huge.  

* Created libpar2, a library for Par1/Par2. 
  ** libpar2.h/.cpp contains enum types and interface
  ** Moved all output from cout/cerr to a parameter called sout/serr.
  ** commandline.h/cpp no longer passes filesize in ExtraFiles type.
  ** setting the number of threads was moved out of commandline.h/.cpp
  ** commandline::Parse now computes blocksize and recoveryblockcount

* Other Features
  ** # ifdefs now properly check for _WIN32 instead of WIN32.  
  ** memorysize is now calculated on Linux and OSX systems.
  ** Default memorysize upped from 16MB to 128MB.
  ** unit tests for libpar2.h/cpp, diskfile.h/cpp, commandline.h/cpp
  ** support cross-compiling with MinGW on Linux
  ** can run tests with Wine (for Windows binaries on Linux)
  ** can run tests with Valgrind, to detect memory leaks
  ** prevents attackers from writing files to absolute paths or parent directories.
  ** warns user when filenames are changed to prevent illegal chars or absolute paths or parent directories
  ** a tiny bit faster, thanks to things found by Cppcheck (e.g., using "while(!list.empty())" instead of "while(list.size()>0)".

* Bug Fixes
  ** I believe the old code violated the standard by writing Windows-style slashes into the Par file's filenames.  That was fixed.  (Decoding still treats Windows-style slashes as UNIX-style slashes, with a warning.)
  ** commandline parsing mishandled "--anything"
  ** DiskFile::Delete() now sets "exists" to false.
  ** Fixed memory leak found by Valgrind
  ** Fixed many bugs found by Cppcheck (correct use of unsigned ints, unused values, uninitialized values)

* Other
  ** added my name to copyright
  ** changed output of "par2 --help"
  ** ordered variables in commandline.h and code was changed to match the order
  ** added "const" or "const &" to a lot of parameters

I'm going to work on documenting Cppcheck, Valgrind, MinGW, and Wine support.  And testing that files generated with the old code work with the new code.  I'll probably be ready with a final version this coming week.  **Please help me find bugs by compiling and running tests on your system right away.**

### CODE REVIEW

**Comment by Rhialto** [comment]
Thanks for doing this!

When running `automake.sh` I get some warnings:
```
/usr/pkg/share/aclocal/autotrace.m4:7: warning: underquoted definition of AM_PATH_AUTOTRACE
/usr/pkg/share/aclocal/autotrace.m4:7:   run info Automake 'Extending aclocal'
/usr/pkg/share/aclocal/autotrace.m4:7:   or see https://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
/usr/pkg/share/automake-1.16/am/library.am: warning: 'libpar2.a': linking libraries using a non-POSIX
/usr/pkg/share/automake-1.16/am/library.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
Makefile.am:24:   while processing library 'libpar2.a'
```
Not sure what you can do about that (or even if the master branch might have the same problem). My autotools are version 1.16.1.
Configure runs fine, by the looks of it, but make fails:
```
murthe:.../scratch2/tmp/par2cmdline$ gmake
gmake  all-am
gmake[1]: Entering directory '/mnt/scratch/scratch2/tmp/par2cmdline'
depbase=`echo src/par2cmdline.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I.    -Wall -fopenmp -g -O2 -MT src/par2cmdline.o -MD -MP -MF $depbase.Tpo -c -o src/par2cmdline.o src/par2cmdline.cpp &&\
mv -f $depbase.Tpo $depbase.Po
src/par2cmdline.cpp:42:3: warning: identifier 'static_assert' is a keyword in C++11 [-Wc++0x-compat]
   static_assert(sizeof(u8) == 1 || sizeof(i8) == 1
   ^
In file included from src/commandline.h:32:0,
                 from src/par2cmdline.cpp:21:
src/diskfile.h:100:15: error: 'unique_ptr' in namespace 'std' does not name a template type
   static std::unique_ptr< list<string> > FindFiles(string path, string wildcard, bool recursive);
               ^
src/par2cmdline.cpp: In function 'int main(int, char**)':
src/par2cmdline.cpp:46:51: error: 'static_assert' was not declared in this scope
   "Error: the assumed sizes of integers is wrong!");
                                                   ^
gmake[1]: *** [Makefile:1003: src/par2cmdline.o] Error 1
```
My first suspicion is that you need to specify the C++ version explicitly on the compiler command line. My g++ is version "gcc version 5.5.0 (nb2 20180327)". I'm not sure how to make it tell me which C++ version it uses by default.

**Comment by mdnahas** [comment]
You said "requires 'AM_PROG_AR' in 'configure.ac'".  When I made the library, there was a webpage that mentioned that it might be necessary on Windows.  The line is in configure.ac, but commented out.  I've uncommented it.   You'll need to run "automake --add-missing"

[https://stackoverflow.com/questions/9766568/unique-ptr-compile-error](https://stackoverflow.com/questions/9766568/unique-ptr-compile-error) says you're right.  It's probably using 2003 version of C++ and std::unique_ptr is in the 2011 version of C++.  I've added "-std=c++11" to AM_CXXFLAGS in Makefile.am.

**Comment by Rhialto** [comment]
I tried it again, and now it builds and tests pass!
```
============================================================================
Testsuite summary for par2cmdline 0.8.0
============================================================================
# TOTAL: 37
# PASS:  37
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
Thanks!

**Comment by mdnahas** [comment]
@Rhialto  Was that just gcc for Linux and MacOS/OSX?   Or did you also try Microsoft Visual C++?

**Comment by Rhialto** [comment]
Oh of course, I should have mentioned. I tried NetBSD/amd64 8.0. I didn't try Linux or MacOS. Maybe I can try MacOS at a later time.

**Comment by mdnahas** [comment]
I've been comparing the output of par2cmdline between master and this branch, for both Linux and Windows (when compiled with MinGW and run using WINE).  

**I can confirm that the Windows version from the master branch does not match the specification.** The filename slashes are Windows-style slashes ('\') not HTML/UNIX-style slashes ('/').    

The output from both versions of this branch are identical, byte for byte.  They differ from the output of the master branch for Linux.  I've looked at the files in a binary editor and it might just be the ordering of packets.  But, then, I don't think I changed any code that affected the ordering of packets.  I'm still investigating that.

**Comment by mdnahas** [comment]
I think I found out why the master branch and this branch were producing different Par2 files, when both are run on Linux.  I have OMP and the order of critical packets depends on threading in par2creator::OpenSourceFiles().  I'll try to confirm it tomorrow.

**Comment by mdnahas** [comment]
Added sorting to critical packets.  When I add that change to master, this branch produces the same result as the master branch on Linux, MinGW+WINE, and OSX.

The code looks good.  I still need to update documentation, etc..

Has anyone run it with Microsoft Visual C++ + Windows?

**Comment by mdnahas** [comment]
I'm done the documentation changes that I wanted to do.

The commit will be ready to push when:
* someone does a code review, especially the commits marked "DANGEROUS"
* someone has compiled the code and run tests using Microsoft Visual C++

**Comment by Rhialto** [comment]
I just tried it on MacOS 10.14.4, and all is well. I had to install automake and autoconf in addition to what I had already, but that is of course to be expected. I use MacPorts for that.

All 33 tests passed.

There was just 2 warnings while compiling:
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
depbase=`echo src/par2cmdline.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
    g++ -DHAVE_CONFIG_H -I.    -Wall  -g -O2 -MT src/par2cmdline.o -MD -MP -MF $depbase.Tpo -c -o src/par2cmdline.o src/par2cmdline.cpp &&\
    mv -f $depbase.Tpo $depbase.Po
src/par2cmdline.cpp:75:18: warning: comparison of two values with different enumeration types in switch statement
      ('CommandLine::Version' and 'CommandLine::Operation') [-Wenum-compare-switch]
            case CommandLine::opNone:
                 ^~~~~~~~~~~~~~~~~~~
src/par2cmdline.cpp:99:18: warning: comparison of two values with different enumeration types in switch statement
      ('CommandLine::Version' and 'CommandLine::Operation') [-Wenum-compare-switch]
            case CommandLine::opNone:
                 ^~~~~~~~~~~~~~~~~~~
2 warnings generated.
```

**Comment by mdnahas** [comment]
@Rhialto Thanks!  I only found one misuse of opNone.   Can you re-run on OSX and see if that fixed both warnings?

**Comment by Rhialto** [comment]
On Wed 15 May 2019 at 14:10:32 -0700, Michael Nahas wrote:
> @Rhialto Thanks!  I only found one misuse of opNone.   Can you re-run on OSX and see if that fixed both warnings?

I think I may have tested the wrong branch before, but at least now
there was no such warning anymore. In the middle there was some warning
from ar (I think) about a file containing no symbols, but apparently
that wasn't a real problem.

**Comment by mdnahas** [comment]
Are we happy with this code? 

I'd like to merge it.  I've got another change already set to push. 
(Allow read/writes of more than 4GB: https://github.com/mdnahas/par2cmdline/tree/long_read_write)

**Comment by BlackIkeEagle** [comment]
I've had no time to check the builds and operation with VC++

**Comment by BlackIkeEagle** [comment]
There are some warnings poping up with gcc 8.3

```
g++ -DHAVE_CONFIG_H -I.    -Wall -std=c++11 -fopenmp -O3 -pipe -fstack-protector-strong -MT src/par1repairer.o -MD -MP -MF $depbase.Tpo -c -o src/par1repairer.o src/par1repairer.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from src/par2cmdline.h:222,
                 from src/par1repairer.cpp:21:
src/reedsolomon.h: In instantiation of ‘bool ReedSolomon<g>::Compute(NoiseLevel, std::ostream&, std::ostream&) [with g = Galois<8, 285, unsigned char>; std::ostream = std::basic_ostream<char>]’:
src/par1repairer.cpp:1265:51:   required from here
src/reedsolomon.h:254:9: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘ReedSolomon<Galois<8, 285, unsigned char> >::G’ {aka ‘class Galois<8, 285, unsigned char>’} with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
   memset(leftmatrix, 0, outcount * incount * sizeof(G));
   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/par2cmdline.h:218,
                 from src/par1repairer.cpp:21:
src/galois.h:57:7: note: ‘ReedSolomon<Galois<8, 285, unsigned char> >::G’ {aka ‘class Galois<8, 285, unsigned char>’} declared here
 class Galois
       ^~~~~~
In file included from src/par2cmdline.h:222,
                 from src/par1repairer.cpp:21:
src/reedsolomon.h:262:11: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘ReedSolomon<Galois<8, 285, unsigned char> >::G’ {aka ‘class Galois<8, 285, unsigned char>’} with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
     memset(rightmatrix, 0, outcount *outcount * sizeof(G));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/par2cmdline.h:218,
                 from src/par1repairer.cpp:21:
src/galois.h:57:7: note: ‘ReedSolomon<Galois<8, 285, unsigned char> >::G’ {aka ‘class Galois<8, 285, unsigned char>’} declared here
 class Galois
       ^~~~~~
```

```
g++ -DHAVE_CONFIG_H -I.    -Wall -std=c++11 -fopenmp -O3 -pipe -fstack-protector-strong -MT src/par2creator.o -MD -MP -MF $depbase.Tpo -c -o src/par2creator.o src/par2creator.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from src/par2cmdline.h:222,
                 from src/par2creator.cpp:21:
src/reedsolomon.h: In instantiation of ‘bool ReedSolomon<g>::Compute(NoiseLevel, std::ostream&, std::ostream&) [with g = Galois<16, 69643, short unsigned int>; std::ostream = std::basic_ostream<char>]’:
src/par2creator.cpp:734:41:   required from here
src/reedsolomon.h:254:9: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘ReedSolomon<Galois<16, 69643, short unsigned int> >::G’ {aka ‘class Galois<16, 69643, short unsigned int>’} with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
   memset(leftmatrix, 0, outcount * incount * sizeof(G));
   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/par2cmdline.h:218,
                 from src/par2creator.cpp:21:
src/galois.h:57:7: note: ‘ReedSolomon<Galois<16, 69643, short unsigned int> >::G’ {aka ‘class Galois<16, 69643, short unsigned int>’} declared here
 class Galois
       ^~~~~~
In file included from src/par2cmdline.h:222,
                 from src/par2creator.cpp:21:
src/reedsolomon.h:262:11: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘ReedSolomon<Galois<16, 69643, short unsigned int> >::G’ {aka ‘class Galois<16, 69643, short unsigned int>’} with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
     memset(rightmatrix, 0, outcount *outcount * sizeof(G));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/par2cmdline.h:218,
                 from src/par2creator.cpp:21:
src/galois.h:57:7: note: ‘ReedSolomon<Galois<16, 69643, short unsigned int> >::G’ {aka ‘class Galois<16, 69643, short unsigned int>’} declared here
 class Galois
       ^~~~~~
```

```
g++ -DHAVE_CONFIG_H -I.    -Wall -std=c++11 -fopenmp -O3 -pipe -fstack-protector-strong -MT src/par2repairer.o -MD -MP -MF $depbase.Tpo -c -o src/par2repairer.o src/par2repairer.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from src/par2cmdline.h:222,
                 from src/par2repairer.cpp:21:
src/reedsolomon.h: In instantiation of ‘bool ReedSolomon<g>::Compute(NoiseLevel, std::ostream&, std::ostream&) [with g = Galois<16, 69643, short unsigned int>; std::ostream = std::basic_ostream<char>]’:
src/par2repairer.cpp:2428:51:   required from here
src/reedsolomon.h:254:9: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘ReedSolomon<Galois<16, 69643, short unsigned int> >::G’ {aka ‘class Galois<16, 69643, short unsigned int>’} with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
   memset(leftmatrix, 0, outcount * incount * sizeof(G));
   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/par2cmdline.h:218,
                 from src/par2repairer.cpp:21:
src/galois.h:57:7: note: ‘ReedSolomon<Galois<16, 69643, short unsigned int> >::G’ {aka ‘class Galois<16, 69643, short unsigned int>’} declared here
 class Galois
       ^~~~~~
In file included from src/par2cmdline.h:222,
                 from src/par2repairer.cpp:21:
src/reedsolomon.h:262:11: warning: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘ReedSolomon<Galois<16, 69643, short unsigned int> >::G’ {aka ‘class Galois<16, 69643, short unsigned int>’} with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
     memset(rightmatrix, 0, outcount *outcount * sizeof(G));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/par2cmdline.h:218,
                 from src/par2repairer.cpp:21:
src/galois.h:57:7: note: ‘ReedSolomon<Galois<16, 69643, short unsigned int> >::G’ {aka ‘class Galois<16, 69643, short unsigned int>’} declared here
 class Galois
       ^~~~~~
```

I don't think these are introduced by this PR, so we could move those to an improvement PR

**Comment by mdnahas** [comment]
Yeah, "git blame src/reedsolomon.h" says that is old code causing the error.  You can't just comment out "memset", because galois's default constructor does not give an initial value to the member variable "value".

@BlackIkeEagle Let me know when you're done with VC++.  Also check it against old Par2 files if you have any.  Some might have Windows-style slashes, which the new code should handle.

**Comment by BlackIkeEagle** [comment]
@mdnahas normally the par files in https://github.com/Parchive/par2cmdline/blob/master/tests/subdirdata-par2files-win.tar.gz should have windows style slashes, so that should cover that

I'm not going to hold back on the merge to wait for VC++, I will get to it with time, or someone else will if it lands in master. Then I'm not holding you back.

**Pull request merged**
