### PR TITLE
Tweak wording for new -T option

### PR DESCRIPTION
**Pull request by Safihre**
@jkansanen

### CODE REVIEW

**Comment by jkansanen** [comment]
@Safihre I find the "file verification and creation" part confusing, are you referring par2 verify and create commands or the verification and creation of hashes?

**Comment by Safihre** [comment]
From the code that's what I thought what it does? File verification and creation happens in parallel?

**Comment by jkansanen** [comment]
Example the repair command gets the largest benefit from -T because it verifies all of the files before and repaired (if any) files afterwards.

**Comment by Safihre** [comment]
I'm a bit confused, maybe I shouldn't try to write the text, I didn't make the code so better if you did it :)
Just wanted somehow to add the info that the `-T` affects the file verification and file creation process primarily, so added that.

**Comment by Safihre** [comment]
@jkansanen I tried a different wording. What do you think?

**Comment by jkansanen** [comment]
@Safihre It's better now.
@BlackIkeEagle Any comments?

**Comment by BlackIkeEagle** [comment]
@jkansanen @Safihre I understand the text so its fine by me

**Comment by Safihre** [comment]
@BlackIkeEagle This PR was against the `mttesting` branch so it isn't in the `master` branch yet.

**Comment by BlackIkeEagle** [comment]
@Safihre I just noticed

**Comment by BlackIkeEagle** [comment]
@Safihre now its in

**Pull request merged**
