### PR TITLE
Mttesting

### PR DESCRIPTION
**Pull request by jkansanen**
I've done extensive testing with the new code and didn't find any major issues. The two file/thread default for hashing offers performance gains even on a slow 5400rpm HDD, four or more threads offers better performance with SSDs.

### CODE REVIEW

**Comment by Safihre** [comment]
Hashed is maybe not the best term for people unaware of the workings of par2 to understand. Maybe `verified` is better?

**Comment by jkansanen** [comment]
Verified isn't the right term because it only imples that verify is affected when in fact the create is also. But I don't have a strong opinion on the subject...

**Comment by Safihre** [comment]
Aaah I did not know that. Maybe explain that in the man pages? 
Or in the command-line text `hashing (verification/creation)`?

**Comment by jkansanen** [comment]
@Safihre Patches are welcome

**Comment by BlackIkeEagle** [comment]
@jkansanen do you have time to check why the clang linux version fails on travis?

**Comment by jkansanen** [comment]
@BlackIkeEagle 
Make check fails because:

> ./par2 -h
> 
> ./par2: error while loading shared libraries: libomp.so: cannot open shared object file: No such file or directory
> 
> The command "./par2 -h" exited with 127.


Seems like a issue with travis...

**Comment by Safihre** [comment]
Yes: https://github.com/travis-ci/travis-ci/issues/8613

**Pull request merged**
