### PR TITLE
Adjustments I needed to build on VS2017 Windows

### PR DESCRIPTION
**Pull request by rwtodd**
I had been sticking with v0.8.0 for a while due to build errors on the master branch, but I finally took the time to resolve them.  I'm building with the latest VS2017 toolset.  There were two errors (and this PR has two commits resolving them):

 1. `DEBUG_NEW` was not defined for me when compiling par2cmdline.cpp. I found that `DEBUG_NEW` was defined in par2cmdline.h, and added the `#include` to pull in the definition.
 2. a few of the OpenMP parallel for loops had errors because the loop index `i` was unsigned.  The error I get specifically says it requires `i` to be signed.  (it's [error C3016](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3016?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C3016)%26rd%3Dtrue&view=vs-2019)).  So I changed the `size_t`'s to `int`'s, and as far as I can see dropping from unsigned to signed does no harm here because the counts involved will get nowhere close to 2^31.

I also built these changes on linux  and ran `make check` with no issues.

### CODE REVIEW

**Comment by mdnahas** [comment]
We don't want to include par2cmdline.h into par2cmdline.cpp.  But the blame is all mine.

libpar2.h is the libary's include file.  It's everything in the library that is externally visible.  It is all that par2cmdline.cpp should need, since it is using the library's interface.  

par2cmdline.h is an include file for things _internal_ to the library.  I left the name as par2cmdline.h because I didn't want to change the file's name and change every include.  But that was a mistake.  Sorry rwtodd.  It's obvious from this fork pull request that we need to change it, so that it is clear and including it doesn't happen again.

But that still leaves:
(1) what to name the include file? Maybe "libpar2internal.h"?
(2) where do we put DEBUG_NEW?  I'd probably copy the definition into commandline.h, near the "#ifdef _WIN32" call.   (The files that are external to the library are commandline.h/cpp and par2cmdline.cpp.)


FYI, Sawada Yutaka emailed me.  He had tried to compile with Visual Studio 2008 (Visual C++ 9.0).  It have a definition for "unique_ptr", which was defined by C++ 2011.  I thought most people would have it by now.  Do we want to change it or include our own version of unique_ptr?

**Comment by rwtodd** [comment]
hmm, commandline.cpp also includes par2cmdline.h.  Based on your comment, I guess this should also change?  I can take care of this if you like (and the rename to libpar2internal.h).

If the project wants to support VS2008 (11 years old now), then maybe a pre-C++11 configuration can use std::auto_ptr, which for basic uses is identical to unique_ptr.  Possibly even #define unique_ptr auto_ptr or a typedef could do the trick.

**Comment by rwtodd** [comment]
Ok, I took a shot at the rename, and the associated cleanup needed to get par2cmdline.cpp and commandline.cpp building again.  It's in a third commit in this PR now.  Let me know what you think.

**Comment by mdnahas** [comment]
"make && make check"  runs clean on my Linux machine, natively and under MinGW/WINE. 

The code looks fine.  We should think about what to do in the future with the #defines that are getting duplicated in libpar2internal.h and commandline.cpp.  I'm not sure there's an easy answer.

I'll run the code on my old OSX box when I get home.  If it looks good there, I'll merge the commits.

**Comment by mdnahas** [comment]
Works on OSX 10.13.6 High Sierra.   

Merging.

**Pull request merged**
